[project]
name = "basic-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rVimal Rawat", email = "vimal.biochem@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "openai>=1.0.0",
    "pydantic>=2.0.0",
    "python-dotenv>=1.0.0",
    "pypdf>=5.0.0",
]

[project.scripts]
basic-rag = "basic_rag:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
